import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useRouter } from 'next/router'

export default function Home() {
  const router = useRouter();

  const task1 = (e) => {
    e.preventDefault()
    router.push('https://chatbot-f6393.web.app/')
  }

  const task2 = (e) => {
    e.preventDefault()
    router.push('https://subscription-gateway.netlify.app')
  }


  return (
    <div className={styles.container}>
      <Head>
        <title>Task Assingment</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.btn}>
        <span style={{ margin: "10px", textDecoration:"underline", fontSize: "25px", color: "white", }}>Integrate ChatBot with Authentication of users. Users can ask Programming related Questions.</span>
        <button style={{padding:"35px", cursor: "pointer", marginBottom: "80px", fontFamily: "700", fontSize: "50px", backgroundColor: "black", color: "white", borderRadius: "12px"}} onClick={task1}> task 1</button>
        <span style={{ margin: "10px", textDecoration:"underline", fontSize: "25px", color: "white", }}>It will be a subscripton task where User can post Question on Stack overflow by give payment using Payment gateway. </span>
        <button style={{padding:"35px", cursor: "pointer", marginBottom: "80px", fontFamily: "700",  fontSize: "50px", backgroundColor: "black", color: "white", borderRadius: "12px"}} onClick={task2}> task 2</button>
      </div>
      
    </div>
  )
}
